---
#
#
# Consul
#
# For detailed options, please refer to: https://galaxy.ansible.com/brianshumate/consul
#
#
- hosts: consul_instances
  become: true
  become_user: root
  roles:
    - {role: brianshumate.consul, tags: ['consul']}
  vars:
    consul_version: 1.10.0
    consul_iface: eth0
    consul_datacenter: "dc1"
    consul_acl_datacenter: "dc1"
    consul_domain: "consul"
    consul_recursors: ['8.8.8.8']
    consul_client_address: "0.0.0.0"
    consul_dnsmasq_enable: yes
    consul_acl_master_token_display: yes
